name: Update nightly release

on: 
  workflow_dispatch:
    inputs:
      revision:
        description: The version in the title of the release.
        required: true

jobs:
  nightly-release:
    runs-on: ubuntu-latest
    steps: 
      - uses: bluwy/substitute-string-action@v3
        name: Create tag name
        id: tag-name
        with:
          _input-text: "${{github.ref_name}}"
          release: nightly
      - name: Update nightly release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.tag-name.outputs.result }}"
          name: "v${{ github.event.inputs.revision }} (nightly)"
          draft: false
          prerelease: true
          body: |
            Nightly version: 
            ```
            ${{ github.event.inputs.revision }}
            ```
            
            **Get the Webapp**
            [Download from Nexus](https://nexus.frankframework.org/repository/releases/org/frankframework/frankframework-webapp/${{ github.event.inputs.revision }}/frankframework-webapp-${{ github.event.inputs.revision }}.war)

            **Get the Docker image**
            You can pull the Docker image with `docker pull frankframework/frankframework:${{ github.event.inputs.revision }}` or [visit the image on DockerHub](https://hub.docker.com/r/frankframework/frankframework/tags?page=&page_size=&ordering=&name=${{ github.event.inputs.revision }})
            
            
